giversion: '3.8'

services:
  db:
    image: harishreddy1234/db:v1.1
    container_name: db
    environment:
      POSTGRES_DB: global_real_estates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - projectnetwork

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=global_real_estates
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    networks:
      - projectnetwork
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://localhost:8000
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - projectnetwork

volumes:
  pgdata:
  backend_media:

networks:
  projectnetwork:
    driver: bridge
