FROM rootpublic/postgis:13-3.5-bookworm-slim

# Optionally set environment variables (for clarity only)
ENV POSTGRES_DB=global_real_estates
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
EXPOSE 5432

