from django.core.management.base import BaseCommand
from core.models import IndiaLocation

class Command(BaseCommand):
    help = 'Populate sample location data for testing'

    def handle(self, *args, **options):
        # Sample location data for testing
        sample_locations = [
            # Maharashtra
            {'state': 'Maharashtra', 'district': 'Mumbai City', 'sub_district': 'Mumbai City', 'village': 'Fort', 'pin_code': '400001'},
            {'state': 'Maharashtra', 'district': 'Mumbai Suburban', 'sub_district': 'Mumbai Suburban', 'village': 'Andheri', 'pin_code': '400058'},
            {'state': 'Maharashtra', 'district': 'Mumbai Suburban', 'sub_district': 'Mumbai Suburban', 'village': 'Bandra', 'pin_code': '400050'},
            {'state': 'Maharashtra', 'district': 'Mumbai Suburban', 'sub_district': 'Mumbai Suburban', 'village': 'Juhu', 'pin_code': '400049'},
            {'state': 'Maharashtra', 'district': 'Pune', 'sub_district': 'Pune City', 'village': 'Koregaon Park', 'pin_code': '411001'},
            {'state': 'Maharashtra', 'district': 'Pune', 'sub_district': 'Pune City', 'village': 'Baner', 'pin_code': '411045'},
            {'state': 'Maharashtra', 'district': 'Nagpur', 'sub_district': 'Nagpur City', 'village': 'Civil Lines', 'pin_code': '440001'},
            {'state': 'Maharashtra', 'district': 'Nagpur', 'sub_district': 'Nagpur City', 'village': 'Sadar', 'pin_code': '440001'},
            {'state': 'Maharashtra', 'district': 'Nashik', 'sub_district': 'Nashik', 'village': 'Nashik', 'pin_code': '422001'},
            {'state': 'Maharashtra', 'district': 'Nashik', 'sub_district': 'Nashik', 'village': 'Satpur', 'pin_code': '422007'},
            {'state': 'Maharashtra', 'district': 'Aurangabad', 'sub_district': 'Aurangabad', 'village': 'Aurangabad', 'pin_code': '431001'},
            {'state': 'Maharashtra', 'district': 'Aurangabad', 'sub_district': 'Aurangabad', 'village': 'Cidco', 'pin_code': '431003'},
            {'state': 'Maharashtra', 'district': 'Thane', 'sub_district': 'Thane', 'village': 'Thane', 'pin_code': '400601'},
            {'state': 'Maharashtra', 'district': 'Thane', 'sub_district': 'Thane', 'village': 'Kalyan', 'pin_code': '421301'},
            {'state': 'Maharashtra', 'district': 'Solapur', 'sub_district': 'Solapur', 'village': 'Solapur', 'pin_code': '413001'},
            {'state': 'Maharashtra', 'district': 'Solapur', 'sub_district': 'Solapur', 'village': 'Akkalkot', 'pin_code': '413216'},
            {'state': 'Maharashtra', 'district': 'Kolhapur', 'sub_district': 'Kolhapur', 'village': 'Kolhapur', 'pin_code': '416001'},
            {'state': 'Maharashtra', 'district': 'Kolhapur', 'sub_district': 'Kolhapur', 'village': 'Shiroli', 'pin_code': '416001'},
            {'state': 'Maharashtra', 'district': 'Amravati', 'sub_district': 'Amravati', 'village': 'Amravati', 'pin_code': '444601'},
            {'state': 'Maharashtra', 'district': 'Amravati', 'sub_district': 'Amravati', 'village': 'Badnera', 'pin_code': '444701'},
            
            # Karnataka
            {'state': 'Karnataka', 'district': 'Bengaluru Urban', 'sub_district': 'Bengaluru Urban', 'village': 'Indiranagar', 'pin_code': '560038'},
            {'state': 'Karnataka', 'district': 'Bengaluru Urban', 'sub_district': 'Bengaluru Urban', 'village': 'Koramangala', 'pin_code': '560034'},
            {'state': 'Karnataka', 'district': 'Bengaluru Urban', 'sub_district': 'Bengaluru Urban', 'village': 'Whitefield', 'pin_code': '560066'},
            {'state': 'Karnataka', 'district': 'Mysuru', 'sub_district': 'Mysuru City', 'village': 'Vijayanagar', 'pin_code': '570017'},
            {'state': 'Karnataka', 'district': 'Mysuru', 'sub_district': 'Mysuru City', 'village': 'Kuvempunagar', 'pin_code': '570023'},
            {'state': 'Karnataka', 'district': 'Mangalore', 'sub_district': 'Mangalore', 'village': 'Mangalore', 'pin_code': '575001'},
            {'state': 'Karnataka', 'district': 'Mangalore', 'sub_district': 'Mangalore', 'village': 'Kadri', 'pin_code': '575002'},
            {'state': 'Karnataka', 'district': 'Hubli', 'sub_district': 'Hubli', 'village': 'Hubli', 'pin_code': '580020'},
            {'state': 'Karnataka', 'district': 'Hubli', 'sub_district': 'Hubli', 'village': 'Dharwad', 'pin_code': '580001'},
            {'state': 'Karnataka', 'district': 'Belagavi', 'sub_district': 'Belagavi', 'village': 'Belagavi', 'pin_code': '590001'},
            {'state': 'Karnataka', 'district': 'Belagavi', 'sub_district': 'Belagavi', 'village': 'Khanapur', 'pin_code': '591302'},
            {'state': 'Karnataka', 'district': 'Kalaburagi', 'sub_district': 'Kalaburagi', 'village': 'Kalaburagi', 'pin_code': '585101'},
            {'state': 'Karnataka', 'district': 'Kalaburagi', 'sub_district': 'Kalaburagi', 'village': 'Sedam', 'pin_code': '585222'},
            {'state': 'Karnataka', 'district': 'Davanagere', 'sub_district': 'Davanagere', 'village': 'Davanagere', 'pin_code': '577001'},
            {'state': 'Karnataka', 'district': 'Davanagere', 'sub_district': 'Davanagere', 'village': 'Harihar', 'pin_code': '577601'},
            {'state': 'Karnataka', 'district': 'Ballari', 'sub_district': 'Ballari', 'village': 'Ballari', 'pin_code': '583101'},
            {'state': 'Karnataka', 'district': 'Ballari', 'sub_district': 'Ballari', 'village': 'Hospet', 'pin_code': '583201'},
            {'state': 'Karnataka', 'district': 'Tumakuru', 'sub_district': 'Tumakuru', 'village': 'Tumakuru', 'pin_code': '572101'},
            {'state': 'Karnataka', 'district': 'Tumakuru', 'sub_district': 'Tumakuru', 'village': 'Sira', 'pin_code': '572137'},
            {'state': 'Karnataka', 'district': 'Shivamogga', 'sub_district': 'Shivamogga', 'village': 'Shivamogga', 'pin_code': '577201'},
            {'state': 'Karnataka', 'district': 'Shivamogga', 'sub_district': 'Shivamogga', 'village': 'Bhadravathi', 'pin_code': '577301'},
            
            # Tamil Nadu
            {'state': 'Tamil Nadu', 'district': 'Chennai', 'sub_district': 'Chennai City', 'village': 'T Nagar', 'pin_code': '600017'},
            {'state': 'Tamil Nadu', 'district': 'Chennai', 'sub_district': 'Chennai City', 'village': 'Anna Nagar', 'pin_code': '600040'},
            {'state': 'Tamil Nadu', 'district': 'Chennai', 'sub_district': 'Chennai City', 'village': 'Adyar', 'pin_code': '600020'},
            {'state': 'Tamil Nadu', 'district': 'Coimbatore', 'sub_district': 'Coimbatore', 'village': 'Coimbatore', 'pin_code': '641001'},
            {'state': 'Tamil Nadu', 'district': 'Coimbatore', 'sub_district': 'Coimbatore', 'village': 'Peelamedu', 'pin_code': '641004'},
            {'state': 'Tamil Nadu', 'district': 'Madurai', 'sub_district': 'Madurai', 'village': 'Madurai', 'pin_code': '625001'},
            {'state': 'Tamil Nadu', 'district': 'Madurai', 'sub_district': 'Madurai', 'village': 'K K Nagar', 'pin_code': '625020'},
            {'state': 'Tamil Nadu', 'district': 'Tiruchirappalli', 'sub_district': 'Tiruchirappalli', 'village': 'Tiruchirappalli', 'pin_code': '620001'},
            {'state': 'Tamil Nadu', 'district': 'Tiruchirappalli', 'sub_district': 'Tiruchirappalli', 'village': 'Srirangam', 'pin_code': '620006'},
            {'state': 'Tamil Nadu', 'district': 'Salem', 'sub_district': 'Salem', 'village': 'Salem', 'pin_code': '636001'},
            {'state': 'Tamil Nadu', 'district': 'Salem', 'sub_district': 'Salem', 'village': 'Attur', 'pin_code': '636102'},
            {'state': 'Tamil Nadu', 'district': 'Tirunelveli', 'sub_district': 'Tirunelveli', 'village': 'Tirunelveli', 'pin_code': '627001'},
            {'state': 'Tamil Nadu', 'district': 'Tirunelveli', 'sub_district': 'Tirunelveli', 'village': 'Palayamkottai', 'pin_code': '627002'},
            {'state': 'Tamil Nadu', 'district': 'Erode', 'sub_district': 'Erode', 'village': 'Erode', 'pin_code': '638001'},
            {'state': 'Tamil Nadu', 'district': 'Erode', 'sub_district': 'Erode', 'village': 'Bhavani', 'pin_code': '638301'},
            {'state': 'Tamil Nadu', 'district': 'Thanjavur', 'sub_district': 'Thanjavur', 'village': 'Thanjavur', 'pin_code': '613001'},
            {'state': 'Tamil Nadu', 'district': 'Thanjavur', 'sub_district': 'Thanjavur', 'village': 'Kumbakonam', 'pin_code': '612001'},
            {'state': 'Tamil Nadu', 'district': 'Dindigul', 'sub_district': 'Dindigul', 'village': 'Dindigul', 'pin_code': '624001'},
            {'state': 'Tamil Nadu', 'district': 'Dindigul', 'sub_district': 'Dindigul', 'village': 'Palani', 'pin_code': '624601'},
            {'state': 'Tamil Nadu', 'district': 'Tiruppur', 'sub_district': 'Tiruppur', 'village': 'Tiruppur', 'pin_code': '641601'},
            {'state': 'Tamil Nadu', 'district': 'Tiruppur', 'sub_district': 'Tiruppur', 'village': 'Avinashi', 'pin_code': '641654'},
            
            # Uttar Pradesh
            {'state': 'Uttar Pradesh', 'district': 'Lucknow', 'sub_district': 'Lucknow', 'village': 'Hazratganj', 'pin_code': '226001'},
            {'state': 'Uttar Pradesh', 'district': 'Lucknow', 'sub_district': 'Lucknow', 'village': 'Gomti Nagar', 'pin_code': '226010'},
            {'state': 'Uttar Pradesh', 'district': 'Kanpur Nagar', 'sub_district': 'Kanpur Nagar', 'village': 'Civil Lines', 'pin_code': '208001'},
            {'state': 'Uttar Pradesh', 'district': 'Kanpur Nagar', 'sub_district': 'Kanpur Nagar', 'village': 'Kakadeo', 'pin_code': '208025'},
            {'state': 'Uttar Pradesh', 'district': 'Agra', 'sub_district': 'Agra', 'village': 'Tajganj', 'pin_code': '282001'},
            {'state': 'Uttar Pradesh', 'district': 'Agra', 'sub_district': 'Agra', 'village': 'Sikandra', 'pin_code': '282007'},
            {'state': 'Uttar Pradesh', 'district': 'Varanasi', 'sub_district': 'Varanasi', 'village': 'Cantt', 'pin_code': '221002'},
            {'state': 'Uttar Pradesh', 'district': 'Varanasi', 'sub_district': 'Varanasi', 'village': 'Bhelupur', 'pin_code': '221010'},
            {'state': 'Uttar Pradesh', 'district': 'Allahabad', 'sub_district': 'Allahabad', 'village': 'Civil Lines', 'pin_code': '211001'},
            {'state': 'Uttar Pradesh', 'district': 'Allahabad', 'sub_district': 'Allahabad', 'village': 'Katju Nagar', 'pin_code': '211002'},
            {'state': 'Uttar Pradesh', 'district': 'Meerut', 'sub_district': 'Meerut', 'village': 'Meerut', 'pin_code': '250001'},
            {'state': 'Uttar Pradesh', 'district': 'Meerut', 'sub_district': 'Meerut', 'village': 'Delhi Road', 'pin_code': '250002'},
            {'state': 'Uttar Pradesh', 'district': 'Ghaziabad', 'sub_district': 'Ghaziabad', 'village': 'Ghaziabad', 'pin_code': '201001'},
            {'state': 'Uttar Pradesh', 'district': 'Ghaziabad', 'sub_district': 'Ghaziabad', 'village': 'Vasundhara', 'pin_code': '201012'},
            {'state': 'Uttar Pradesh', 'district': 'Bareilly', 'sub_district': 'Bareilly', 'village': 'Bareilly', 'pin_code': '243001'},
            {'state': 'Uttar Pradesh', 'district': 'Bareilly', 'sub_district': 'Bareilly', 'village': 'Civil Lines', 'pin_code': '243001'},
            {'state': 'Uttar Pradesh', 'district': 'Gorakhpur', 'sub_district': 'Gorakhpur', 'village': 'Gorakhpur', 'pin_code': '273001'},
            {'state': 'Uttar Pradesh', 'district': 'Gorakhpur', 'sub_district': 'Gorakhpur', 'village': 'Cantt', 'pin_code': '273001'},
            {'state': 'Uttar Pradesh', 'district': 'Jhansi', 'sub_district': 'Jhansi', 'village': 'Jhansi', 'pin_code': '284001'},
            {'state': 'Uttar Pradesh', 'district': 'Jhansi', 'sub_district': 'Jhansi', 'village': 'Cantt', 'pin_code': '284001'},
            
            # Rajasthan
            {'state': 'Rajasthan', 'district': 'Jaipur', 'sub_district': 'Jaipur', 'village': 'Pink City', 'pin_code': '302001'},
            {'state': 'Rajasthan', 'district': 'Jaipur', 'sub_district': 'Jaipur', 'village': 'C-Scheme', 'pin_code': '302001'},
            {'state': 'Rajasthan', 'district': 'Jaipur', 'sub_district': 'Jaipur', 'village': 'Vaishali Nagar', 'pin_code': '302021'},
            {'state': 'Rajasthan', 'district': 'Jodhpur', 'sub_district': 'Jodhpur', 'village': 'Jodhpur', 'pin_code': '342001'},
            {'state': 'Rajasthan', 'district': 'Jodhpur', 'sub_district': 'Jodhpur', 'village': 'Cantt', 'pin_code': '342001'},
            {'state': 'Rajasthan', 'district': 'Udaipur', 'sub_district': 'Udaipur', 'village': 'Udaipur', 'pin_code': '313001'},
            {'state': 'Rajasthan', 'district': 'Udaipur', 'sub_district': 'Udaipur', 'village': 'Fateh Sagar', 'pin_code': '313001'},
            {'state': 'Rajasthan', 'district': 'Kota', 'sub_district': 'Kota', 'village': 'Kota', 'pin_code': '324001'},
            {'state': 'Rajasthan', 'district': 'Kota', 'sub_district': 'Kota', 'village': 'Cantt', 'pin_code': '324001'},
            {'state': 'Rajasthan', 'district': 'Ajmer', 'sub_district': 'Ajmer', 'village': 'Ajmer', 'pin_code': '305001'},
            {'state': 'Rajasthan', 'district': 'Ajmer', 'sub_district': 'Ajmer', 'village': 'Cantt', 'pin_code': '305001'},
            {'state': 'Rajasthan', 'district': 'Bikaner', 'sub_district': 'Bikaner', 'village': 'Bikaner', 'pin_code': '334001'},
            {'state': 'Rajasthan', 'district': 'Bikaner', 'sub_district': 'Bikaner', 'village': 'Cantt', 'pin_code': '334001'},
            {'state': 'Rajasthan', 'district': 'Alwar', 'sub_district': 'Alwar', 'village': 'Alwar', 'pin_code': '301001'},
            {'state': 'Rajasthan', 'district': 'Alwar', 'sub_district': 'Alwar', 'village': 'Cantt', 'pin_code': '301001'},
            {'state': 'Rajasthan', 'district': 'Bharatpur', 'sub_district': 'Bharatpur', 'village': 'Bharatpur', 'pin_code': '321001'},
            {'state': 'Rajasthan', 'district': 'Bharatpur', 'sub_district': 'Bharatpur', 'village': 'Cantt', 'pin_code': '321001'},
            {'state': 'Rajasthan', 'district': 'Sikar', 'sub_district': 'Sikar', 'village': 'Sikar', 'pin_code': '332001'},
            {'state': 'Rajasthan', 'district': 'Sikar', 'sub_district': 'Sikar', 'village': 'Cantt', 'pin_code': '332001'},
            
            # Madhya Pradesh
            {'state': 'Madhya Pradesh', 'district': 'Bhopal', 'sub_district': 'Bhopal', 'village': 'Bhopal', 'pin_code': '462001'},
            {'state': 'Madhya Pradesh', 'district': 'Bhopal', 'sub_district': 'Bhopal', 'village': 'Cantt', 'pin_code': '462001'},
            {'state': 'Madhya Pradesh', 'district': 'Indore', 'sub_district': 'Indore', 'village': 'Indore', 'pin_code': '452001'},
            {'state': 'Madhya Pradesh', 'district': 'Indore', 'sub_district': 'Indore', 'village': 'Cantt', 'pin_code': '452001'},
            {'state': 'Madhya Pradesh', 'district': 'Gwalior', 'sub_district': 'Gwalior', 'village': 'Gwalior', 'pin_code': '474001'},
            {'state': 'Madhya Pradesh', 'district': 'Gwalior', 'sub_district': 'Gwalior', 'village': 'Cantt', 'pin_code': '474001'},
            {'state': 'Madhya Pradesh', 'district': 'Jabalpur', 'sub_district': 'Jabalpur', 'village': 'Jabalpur', 'pin_code': '482001'},
            {'state': 'Madhya Pradesh', 'district': 'Jabalpur', 'sub_district': 'Jabalpur', 'village': 'Cantt', 'pin_code': '482001'},
            {'state': 'Madhya Pradesh', 'district': 'Ujjain', 'sub_district': 'Ujjain', 'village': 'Ujjain', 'pin_code': '456001'},
            {'state': 'Madhya Pradesh', 'district': 'Ujjain', 'sub_district': 'Ujjain', 'village': 'Cantt', 'pin_code': '456001'},
            {'state': 'Madhya Pradesh', 'district': 'Sagar', 'sub_district': 'Sagar', 'village': 'Sagar', 'pin_code': '470001'},
            {'state': 'Madhya Pradesh', 'district': 'Sagar', 'sub_district': 'Sagar', 'village': 'Cantt', 'pin_code': '470001'},
            {'state': 'Madhya Pradesh', 'district': 'Rewa', 'sub_district': 'Rewa', 'village': 'Rewa', 'pin_code': '486001'},
            {'state': 'Madhya Pradesh', 'district': 'Rewa', 'sub_district': 'Rewa', 'village': 'Cantt', 'pin_code': '486001'},
            {'state': 'Madhya Pradesh', 'district': 'Satna', 'sub_district': 'Satna', 'village': 'Satna', 'pin_code': '485001'},
            {'state': 'Madhya Pradesh', 'district': 'Satna', 'sub_district': 'Satna', 'village': 'Cantt', 'pin_code': '485001'},
            {'state': 'Madhya Pradesh', 'district': 'Ratlam', 'sub_district': 'Ratlam', 'village': 'Ratlam', 'pin_code': '457001'},
            {'state': 'Madhya Pradesh', 'district': 'Ratlam', 'sub_district': 'Ratlam', 'village': 'Cantt', 'pin_code': '457001'},
            {'state': 'Madhya Pradesh', 'district': 'Morena', 'sub_district': 'Morena', 'village': 'Morena', 'pin_code': '476001'},
            {'state': 'Madhya Pradesh', 'district': 'Morena', 'sub_district': 'Morena', 'village': 'Cantt', 'pin_code': '476001'},
            
            # Himachal Pradesh
            {'state': 'Himachal Pradesh', 'district': 'Shimla', 'sub_district': 'Shimla', 'village': 'Shimla', 'pin_code': '171001'},
            {'state': 'Himachal Pradesh', 'district': 'Shimla', 'sub_district': 'Shimla', 'village': 'Cantt', 'pin_code': '171001'},
            {'state': 'Himachal Pradesh', 'district': 'Kangra', 'sub_district': 'Kangra', 'village': 'Dharamshala', 'pin_code': '176001'},
            {'state': 'Himachal Pradesh', 'district': 'Kangra', 'sub_district': 'Kangra', 'village': 'McLeod Ganj', 'pin_code': '176219'},
            {'state': 'Himachal Pradesh', 'district': 'Mandi', 'sub_district': 'Mandi', 'village': 'Mandi', 'pin_code': '175001'},
            {'state': 'Himachal Pradesh', 'district': 'Mandi', 'sub_district': 'Mandi', 'village': 'Sundernagar', 'pin_code': '174401'},
            {'state': 'Himachal Pradesh', 'district': 'Solan', 'sub_district': 'Solan', 'village': 'Solan', 'pin_code': '173212'},
            {'state': 'Himachal Pradesh', 'district': 'Solan', 'sub_district': 'Solan', 'village': 'Kasauli', 'pin_code': '173204'},
            {'state': 'Himachal Pradesh', 'district': 'Kullu', 'sub_district': 'Kullu', 'village': 'Kullu', 'pin_code': '175101'},
            {'state': 'Himachal Pradesh', 'district': 'Kullu', 'sub_district': 'Kullu', 'village': 'Manali', 'pin_code': '175131'},
            {'state': 'Himachal Pradesh', 'district': 'Hamirpur', 'sub_district': 'Hamirpur', 'village': 'Hamirpur', 'pin_code': '177001'},
            {'state': 'Himachal Pradesh', 'district': 'Hamirpur', 'sub_district': 'Hamirpur', 'village': 'Barsar', 'pin_code': '177021'},
            {'state': 'Himachal Pradesh', 'district': 'Una', 'sub_district': 'Una', 'village': 'Una', 'pin_code': '174303'},
            {'state': 'Himachal Pradesh', 'district': 'Una', 'sub_district': 'Una', 'village': 'Amb', 'pin_code': '177203'},
            {'state': 'Himachal Pradesh', 'district': 'Bilaspur', 'sub_district': 'Bilaspur', 'village': 'Bilaspur', 'pin_code': '174001'},
            {'state': 'Himachal Pradesh', 'district': 'Bilaspur', 'sub_district': 'Bilaspur', 'village': 'Ghumarwin', 'pin_code': '174021'},
            {'state': 'Himachal Pradesh', 'district': 'Chamba', 'sub_district': 'Chamba', 'village': 'Chamba', 'pin_code': '176310'},
            {'state': 'Himachal Pradesh', 'district': 'Chamba', 'sub_district': 'Chamba', 'village': 'Dalhousie', 'pin_code': '176304'},
            {'state': 'Himachal Pradesh', 'district': 'Kinnaur', 'sub_district': 'Kinnaur', 'village': 'Kalpa', 'pin_code': '172108'},
            {'state': 'Himachal Pradesh', 'district': 'Kinnaur', 'sub_district': 'Kinnaur', 'village': 'Reckong Peo', 'pin_code': '172107'},
            {'state': 'Himachal Pradesh', 'district': 'Lahaul and Spiti', 'sub_district': 'Lahaul and Spiti', 'village': 'Keylong', 'pin_code': '175132'},
            {'state': 'Himachal Pradesh', 'district': 'Lahaul and Spiti', 'sub_district': 'Lahaul and Spiti', 'village': 'Kaza', 'pin_code': '172114'},
            {'state': 'Himachal Pradesh', 'district': 'Sirmour', 'sub_district': 'Sirmour', 'village': 'Nahan', 'pin_code': '173001'},
            {'state': 'Himachal Pradesh', 'district': 'Sirmour', 'sub_district': 'Sirmour', 'village': 'Paonta Sahib', 'pin_code': '173025'},
            
            # Jammu and Kashmir
            {'state': 'Jammu and Kashmir', 'district': 'Srinagar', 'sub_district': 'Srinagar', 'village': 'Srinagar', 'pin_code': '190001'},
            {'state': 'Jammu and Kashmir', 'district': 'Srinagar', 'sub_district': 'Srinagar', 'village': 'Dal Lake', 'pin_code': '190001'},
            {'state': 'Jammu and Kashmir', 'district': 'Jammu', 'sub_district': 'Jammu', 'village': 'Jammu', 'pin_code': '180001'},
            {'state': 'Jammu and Kashmir', 'district': 'Jammu', 'sub_district': 'Jammu', 'village': 'Cantt', 'pin_code': '180001'},
            {'state': 'Jammu and Kashmir', 'district': 'Anantnag', 'sub_district': 'Anantnag', 'village': 'Anantnag', 'pin_code': '192101'},
            {'state': 'Jammu and Kashmir', 'district': 'Anantnag', 'sub_district': 'Anantnag', 'village': 'Pahalgam', 'pin_code': '192126'},
            {'state': 'Jammu and Kashmir', 'district': 'Baramulla', 'sub_district': 'Baramulla', 'village': 'Baramulla', 'pin_code': '193101'},
            {'state': 'Jammu and Kashmir', 'district': 'Baramulla', 'sub_district': 'Baramulla', 'village': 'Uri', 'pin_code': '193123'},
            {'state': 'Jammu and Kashmir', 'district': 'Budgam', 'sub_district': 'Budgam', 'village': 'Budgam', 'pin_code': '191111'},
            {'state': 'Jammu and Kashmir', 'district': 'Budgam', 'sub_district': 'Budgam', 'village': 'Chadoora', 'pin_code': '191102'},
            {'state': 'Jammu and Kashmir', 'district': 'Pulwama', 'sub_district': 'Pulwama', 'village': 'Pulwama', 'pin_code': '192301'},
            {'state': 'Jammu and Kashmir', 'district': 'Pulwama', 'sub_district': 'Pulwama', 'village': 'Tral', 'pin_code': '192123'},
            {'state': 'Jammu and Kashmir', 'district': 'Kupwara', 'sub_district': 'Kupwara', 'village': 'Kupwara', 'pin_code': '193222'},
            {'state': 'Jammu and Kashmir', 'district': 'Kupwara', 'sub_district': 'Kupwara', 'village': 'Handwara', 'pin_code': '193221'},
            {'state': 'Jammu and Kashmir', 'district': 'Ganderbal', 'sub_district': 'Ganderbal', 'village': 'Ganderbal', 'pin_code': '191201'},
            {'state': 'Jammu and Kashmir', 'district': 'Ganderbal', 'sub_district': 'Ganderbal', 'village': 'Sonamarg', 'pin_code': '191202'},
            {'state': 'Jammu and Kashmir', 'district': 'Bandipora', 'sub_district': 'Bandipora', 'village': 'Bandipora', 'pin_code': '193502'},
            {'state': 'Jammu and Kashmir', 'district': 'Bandipora', 'sub_district': 'Bandipora', 'village': 'Sumbal', 'pin_code': '193501'},
            {'state': 'Jammu and Kashmir', 'district': 'Kulgam', 'sub_district': 'Kulgam', 'village': 'Kulgam', 'pin_code': '192231'},
            {'state': 'Jammu and Kashmir', 'district': 'Kulgam', 'sub_district': 'Kulgam', 'village': 'Qazigund', 'pin_code': '192123'},
            {'state': 'Jammu and Kashmir', 'district': 'Shopian', 'sub_district': 'Shopian', 'village': 'Shopian', 'pin_code': '192303'},
            {'state': 'Jammu and Kashmir', 'district': 'Shopian', 'sub_district': 'Shopian', 'village': 'Pulwama', 'pin_code': '192301'},
            {'state': 'Jammu and Kashmir', 'district': 'Kathua', 'sub_district': 'Kathua', 'village': 'Kathua', 'pin_code': '184101'},
            {'state': 'Jammu and Kashmir', 'district': 'Kathua', 'sub_district': 'Kathua', 'village': 'Hiranagar', 'pin_code': '184142'},
            {'state': 'Jammu and Kashmir', 'district': 'Samba', 'sub_district': 'Samba', 'village': 'Samba', 'pin_code': '184121'},
            {'state': 'Jammu and Kashmir', 'district': 'Samba', 'sub_district': 'Samba', 'village': 'Vijaypur', 'pin_code': '184102'},
            {'state': 'Jammu and Kashmir', 'district': 'Udhampur', 'sub_district': 'Udhampur', 'village': 'Udhampur', 'pin_code': '182101'},
            {'state': 'Jammu and Kashmir', 'district': 'Udhampur', 'sub_district': 'Udhampur', 'village': 'Cantt', 'pin_code': '182101'},
            {'state': 'Jammu and Kashmir', 'district': 'Reasi', 'sub_district': 'Reasi', 'village': 'Reasi', 'pin_code': '182311'},
            {'state': 'Jammu and Kashmir', 'district': 'Reasi', 'sub_district': 'Reasi', 'village': 'Katra', 'pin_code': '182301'},
            {'state': 'Jammu and Kashmir', 'district': 'Ramban', 'sub_district': 'Ramban', 'village': 'Ramban', 'pin_code': '182144'},
            {'state': 'Jammu and Kashmir', 'district': 'Ramban', 'sub_district': 'Ramban', 'village': 'Banihal', 'pin_code': '182146'},
            {'state': 'Jammu and Kashmir', 'district': 'Doda', 'sub_district': 'Doda', 'village': 'Doda', 'pin_code': '182202'},
            {'state': 'Jammu and Kashmir', 'district': 'Doda', 'sub_district': 'Doda', 'village': 'Bhaderwah', 'pin_code': '182222'},
            {'state': 'Jammu and Kashmir', 'district': 'Kishtwar', 'sub_district': 'Kishtwar', 'village': 'Kishtwar', 'pin_code': '182204'},
            {'state': 'Jammu and Kashmir', 'district': 'Kishtwar', 'sub_district': 'Kishtwar', 'village': 'Chhatroo', 'pin_code': '182204'},
            {'state': 'Jammu and Kashmir', 'district': 'Rajouri', 'sub_district': 'Rajouri', 'village': 'Rajouri', 'pin_code': '185131'},
            {'state': 'Jammu and Kashmir', 'district': 'Rajouri', 'sub_district': 'Rajouri', 'village': 'Nowshera', 'pin_code': '185151'},
            {'state': 'Jammu and Kashmir', 'district': 'Poonch', 'sub_district': 'Poonch', 'village': 'Poonch', 'pin_code': '185101'},
            {'state': 'Jammu and Kashmir', 'district': 'Poonch', 'sub_district': 'Poonch', 'village': 'Surankote', 'pin_code': '185121'},
            
            # Ladakh
            {'state': 'Ladakh', 'district': 'Leh', 'sub_district': 'Leh', 'village': 'Leh', 'pin_code': '194101'},
            {'state': 'Ladakh', 'district': 'Leh', 'sub_district': 'Leh', 'village': 'Cantt', 'pin_code': '194101'},
            {'state': 'Ladakh', 'district': 'Kargil', 'sub_district': 'Kargil', 'village': 'Kargil', 'pin_code': '194103'},
            {'state': 'Ladakh', 'district': 'Kargil', 'sub_district': 'Kargil', 'village': 'Cantt', 'pin_code': '194103'},
            {'state': 'Ladakh', 'district': 'Nubra', 'sub_district': 'Nubra', 'village': 'Diskit', 'pin_code': '194401'},
            {'state': 'Ladakh', 'district': 'Nubra', 'sub_district': 'Nubra', 'village': 'Hunder', 'pin_code': '194401'},
            {'state': 'Ladakh', 'district': 'Zanskar', 'sub_district': 'Zanskar', 'village': 'Padum', 'pin_code': '194301'},
            {'state': 'Ladakh', 'district': 'Zanskar', 'sub_district': 'Zanskar', 'village': 'Rangdum', 'pin_code': '194301'},
            {'state': 'Ladakh', 'district': 'Drass', 'sub_district': 'Drass', 'village': 'Drass', 'pin_code': '194102'},
            {'state': 'Ladakh', 'district': 'Drass', 'sub_district': 'Drass', 'village': 'Kargil', 'pin_code': '194103'},
            {'state': 'Ladakh', 'district': 'Sham', 'sub_district': 'Sham', 'village': 'Alchi', 'pin_code': '194106'},
            {'state': 'Ladakh', 'district': 'Sham', 'sub_district': 'Sham', 'village': 'Likir', 'pin_code': '194106'},
            {'state': 'Ladakh', 'district': 'Changthang', 'sub_district': 'Changthang', 'village': 'Tso Moriri', 'pin_code': '194201'},
            {'state': 'Ladakh', 'district': 'Changthang', 'sub_district': 'Changthang', 'village': 'Tso Kar', 'pin_code': '194201'},
            
            # Jharkhand
            {'state': 'Jharkhand', 'district': 'Ranchi', 'sub_district': 'Ranchi', 'village': 'Ranchi', 'pin_code': '834001'},
            {'state': 'Jharkhand', 'district': 'Ranchi', 'sub_district': 'Ranchi', 'village': 'Cantt', 'pin_code': '834001'},
            {'state': 'Jharkhand', 'district': 'Dhanbad', 'sub_district': 'Dhanbad', 'village': 'Dhanbad', 'pin_code': '826001'},
            {'state': 'Jharkhand', 'district': 'Dhanbad', 'sub_district': 'Dhanbad', 'village': 'Cantt', 'pin_code': '826001'},
            {'state': 'Jharkhand', 'district': 'Bokaro', 'sub_district': 'Bokaro', 'village': 'Bokaro', 'pin_code': '827001'},
            {'state': 'Jharkhand', 'district': 'Bokaro', 'sub_district': 'Bokaro', 'village': 'Steel City', 'pin_code': '827001'},
            {'state': 'Jharkhand', 'district': 'Jamshedpur', 'sub_district': 'East Singhbhum', 'village': 'Jamshedpur', 'pin_code': '831001'},
            {'state': 'Jharkhand', 'district': 'Jamshedpur', 'sub_district': 'East Singhbhum', 'village': 'Tatanagar', 'pin_code': '831001'},
            {'state': 'Jharkhand', 'district': 'Deoghar', 'sub_district': 'Deoghar', 'village': 'Deoghar', 'pin_code': '814112'},
            {'state': 'Jharkhand', 'district': 'Deoghar', 'sub_district': 'Deoghar', 'village': 'Baidyanath', 'pin_code': '814112'},
            {'state': 'Jharkhand', 'district': 'Hazaribagh', 'sub_district': 'Hazaribagh', 'village': 'Hazaribagh', 'pin_code': '825301'},
            {'state': 'Jharkhand', 'district': 'Hazaribagh', 'sub_district': 'Hazaribagh', 'village': 'Cantt', 'pin_code': '825301'},
            {'state': 'Jharkhand', 'district': 'Giridih', 'sub_district': 'Giridih', 'village': 'Giridih', 'pin_code': '815301'},
            {'state': 'Jharkhand', 'district': 'Giridih', 'sub_district': 'Giridih', 'village': 'Usri Falls', 'pin_code': '815301'},
            {'state': 'Jharkhand', 'district': 'Dumka', 'sub_district': 'Dumka', 'village': 'Dumka', 'pin_code': '814101'},
            {'state': 'Jharkhand', 'district': 'Dumka', 'sub_district': 'Dumka', 'village': 'Masalia', 'pin_code': '814101'},
            {'state': 'Jharkhand', 'district': 'Palamu', 'sub_district': 'Palamu', 'village': 'Daltonganj', 'pin_code': '822101'},
            {'state': 'Jharkhand', 'district': 'Palamu', 'sub_district': 'Palamu', 'village': 'Medininagar', 'pin_code': '822101'},
            {'state': 'Jharkhand', 'district': 'Garhwa', 'sub_district': 'Garhwa', 'village': 'Garhwa', 'pin_code': '822114'},
            {'state': 'Jharkhand', 'district': 'Garhwa', 'sub_district': 'Garhwa', 'village': 'Nagpura', 'pin_code': '822114'},
            {'state': 'Jharkhand', 'district': 'Chatra', 'sub_district': 'Chatra', 'village': 'Chatra', 'pin_code': '825401'},
            {'state': 'Jharkhand', 'district': 'Chatra', 'sub_district': 'Chatra', 'village': 'Hunterganj', 'pin_code': '825401'},
            {'state': 'Jharkhand', 'district': 'Koderma', 'sub_district': 'Koderma', 'village': 'Koderma', 'pin_code': '825410'},
            {'state': 'Jharkhand', 'district': 'Koderma', 'sub_district': 'Koderma', 'village': 'Jhumri Telaiya', 'pin_code': '825410'},
            {'state': 'Jharkhand', 'district': 'Latehar', 'sub_district': 'Latehar', 'village': 'Latehar', 'pin_code': '829206'},
            {'state': 'Jharkhand', 'district': 'Latehar', 'sub_district': 'Latehar', 'village': 'Bariatu', 'pin_code': '829206'},
            {'state': 'Jharkhand', 'district': 'Lohardaga', 'sub_district': 'Lohardaga', 'village': 'Lohardaga', 'pin_code': '835302'},
            {'state': 'Jharkhand', 'district': 'Lohardaga', 'sub_district': 'Lohardaga', 'village': 'Kisko', 'pin_code': '835302'},
            {'state': 'Jharkhand', 'district': 'Gumla', 'sub_district': 'Gumla', 'village': 'Gumla', 'pin_code': '835207'},
            {'state': 'Jharkhand', 'district': 'Gumla', 'sub_district': 'Gumla', 'village': 'Basia', 'pin_code': '835207'},
            {'state': 'Jharkhand', 'district': 'Simdega', 'sub_district': 'Simdega', 'village': 'Simdega', 'pin_code': '835223'},
            {'state': 'Jharkhand', 'district': 'Simdega', 'sub_district': 'Simdega', 'village': 'Kolebira', 'pin_code': '835223'},
            {'state': 'Jharkhand', 'district': 'Khunti', 'sub_district': 'Khunti', 'village': 'Khunti', 'pin_code': '835210'},
            {'state': 'Jharkhand', 'district': 'Khunti', 'sub_district': 'Khunti', 'village': 'Murhu', 'pin_code': '835210'},
            {'state': 'Jharkhand', 'district': 'West Singhbhum', 'sub_district': 'West Singhbhum', 'village': 'Chaibasa', 'pin_code': '833201'},
            {'state': 'Jharkhand', 'district': 'West Singhbhum', 'sub_district': 'West Singhbhum', 'village': 'Chakradharpur', 'pin_code': '833201'},
            {'state': 'Jharkhand', 'district': 'Saraikela Kharsawan', 'sub_district': 'Saraikela Kharsawan', 'village': 'Saraikela', 'pin_code': '833219'},
            {'state': 'Jharkhand', 'district': 'Saraikela Kharsawan', 'sub_district': 'Saraikela Kharsawan', 'village': 'Kharsawan', 'pin_code': '833219'},
            {'state': 'Jharkhand', 'district': 'Jamtara', 'sub_district': 'Jamtara', 'village': 'Jamtara', 'pin_code': '815351'},
            {'state': 'Jharkhand', 'district': 'Jamtara', 'sub_district': 'Jamtara', 'village': 'Nala', 'pin_code': '815351'},
            {'state': 'Jharkhand', 'district': 'Pakur', 'sub_district': 'Pakur', 'village': 'Pakur', 'pin_code': '816107'},
            {'state': 'Jharkhand', 'district': 'Pakur', 'sub_district': 'Pakur', 'village': 'Maheshpur', 'pin_code': '816107'},
            {'state': 'Jharkhand', 'district': 'Sahebganj', 'sub_district': 'Sahebganj', 'village': 'Sahebganj', 'pin_code': '816109'},
            {'state': 'Jharkhand', 'district': 'Sahebganj', 'sub_district': 'Sahebganj', 'village': 'Rajmahal', 'pin_code': '816109'},
            {'state': 'Jharkhand', 'district': 'Godda', 'sub_district': 'Godda', 'village': 'Godda', 'pin_code': '814133'},
            {'state': 'Jharkhand', 'district': 'Godda', 'sub_district': 'Godda', 'village': 'Mahagama', 'pin_code': '814133'},
            {'state': 'Jharkhand', 'district': 'Ramgarh', 'sub_district': 'Ramgarh', 'village': 'Ramgarh', 'pin_code': '829103'},
            {'state': 'Jharkhand', 'district': 'Ramgarh', 'sub_district': 'Ramgarh', 'village': 'Cantt', 'pin_code': '829103'},
            
            # Kerala
            {'state': 'Kerala', 'district': 'Thiruvananthapuram', 'sub_district': 'Thiruvananthapuram', 'village': 'Thiruvananthapuram', 'pin_code': '695001'},
            {'state': 'Kerala', 'district': 'Thiruvananthapuram', 'sub_district': 'Thiruvananthapuram', 'village': 'Kowdiar', 'pin_code': '695003'},
            {'state': 'Kerala', 'district': 'Kollam', 'sub_district': 'Kollam', 'village': 'Kollam', 'pin_code': '691001'},
            {'state': 'Kerala', 'district': 'Kollam', 'sub_district': 'Kollam', 'village': 'Ashtamudi', 'pin_code': '691001'},
            {'state': 'Kerala', 'district': 'Pathanamthitta', 'sub_district': 'Pathanamthitta', 'village': 'Pathanamthitta', 'pin_code': '689645'},
            {'state': 'Kerala', 'district': 'Pathanamthitta', 'sub_district': 'Pathanamthitta', 'village': 'Sabarimala', 'pin_code': '689645'},
            {'state': 'Kerala', 'district': 'Alappuzha', 'sub_district': 'Alappuzha', 'village': 'Alappuzha', 'pin_code': '688001'},
            {'state': 'Kerala', 'district': 'Alappuzha', 'sub_district': 'Alappuzha', 'village': 'Kuttanad', 'pin_code': '688001'},
            {'state': 'Kerala', 'district': 'Kottayam', 'sub_district': 'Kottayam', 'village': 'Kottayam', 'pin_code': '686001'},
            {'state': 'Kerala', 'district': 'Kottayam', 'sub_district': 'Kottayam', 'village': 'Kumarakom', 'pin_code': '686563'},
            {'state': 'Kerala', 'district': 'Idukki', 'sub_district': 'Idukki', 'village': 'Idukki', 'pin_code': '685602'},
            {'state': 'Kerala', 'district': 'Idukki', 'sub_district': 'Idukki', 'village': 'Munnar', 'pin_code': '685612'},
            {'state': 'Kerala', 'district': 'Ernakulam', 'sub_district': 'Ernakulam', 'village': 'Kochi', 'pin_code': '682001'},
            {'state': 'Kerala', 'district': 'Ernakulam', 'sub_district': 'Ernakulam', 'village': 'Fort Kochi', 'pin_code': '682001'},
            {'state': 'Kerala', 'district': 'Thrissur', 'sub_district': 'Thrissur', 'village': 'Thrissur', 'pin_code': '680001'},
            {'state': 'Kerala', 'district': 'Thrissur', 'sub_district': 'Thrissur', 'village': 'Guruvayur', 'pin_code': '680101'},
            {'state': 'Kerala', 'district': 'Palakkad', 'sub_district': 'Palakkad', 'village': 'Palakkad', 'pin_code': '678001'},
            {'state': 'Kerala', 'district': 'Palakkad', 'sub_district': 'Palakkad', 'village': 'Malampuzha', 'pin_code': '678651'},
            {'state': 'Kerala', 'district': 'Malappuram', 'sub_district': 'Malappuram', 'village': 'Malappuram', 'pin_code': '676505'},
            {'state': 'Kerala', 'district': 'Malappuram', 'sub_district': 'Malappuram', 'village': 'Manjeri', 'pin_code': '676121'},
            {'state': 'Kerala', 'district': 'Kozhikode', 'sub_district': 'Kozhikode', 'village': 'Kozhikode', 'pin_code': '673001'},
            {'state': 'Kerala', 'district': 'Kozhikode', 'sub_district': 'Kozhikode', 'village': 'Calicut', 'pin_code': '673001'},
            {'state': 'Kerala', 'district': 'Wayanad', 'sub_district': 'Wayanad', 'village': 'Kalpetta', 'pin_code': '673121'},
            {'state': 'Kerala', 'district': 'Wayanad', 'sub_district': 'Wayanad', 'village': 'Sultan Bathery', 'pin_code': '673592'},
            {'state': 'Kerala', 'district': 'Kannur', 'sub_district': 'Kannur', 'village': 'Kannur', 'pin_code': '670001'},
            {'state': 'Kerala', 'district': 'Kannur', 'sub_district': 'Kannur', 'village': 'Payyannur', 'pin_code': '670307'},
            {'state': 'Kerala', 'district': 'Kasaragod', 'sub_district': 'Kasaragod', 'village': 'Kasaragod', 'pin_code': '671121'},
            {'state': 'Kerala', 'district': 'Kasaragod', 'sub_district': 'Kasaragod', 'village': 'Bekal', 'pin_code': '671316'},
            
            # Lakshadweep
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kavaratti', 'village': 'Kavaratti', 'pin_code': '682555'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kavaratti', 'village': 'Capital', 'pin_code': '682555'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Agatti', 'village': 'Agatti', 'pin_code': '682553'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Agatti', 'village': 'Airport', 'pin_code': '682553'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Amini', 'village': 'Amini', 'pin_code': '682552'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Amini', 'village': 'Island', 'pin_code': '682552'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Andrott', 'village': 'Andrott', 'pin_code': '682551'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Andrott', 'village': 'Island', 'pin_code': '682551'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Bitra', 'village': 'Bitra', 'pin_code': '682554'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Bitra', 'village': 'Island', 'pin_code': '682554'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Chetlat', 'village': 'Chetlat', 'pin_code': '682556'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Chetlat', 'village': 'Island', 'pin_code': '682556'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kadmat', 'village': 'Kadmat', 'pin_code': '682557'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kadmat', 'village': 'Island', 'pin_code': '682557'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kalpeni', 'village': 'Kalpeni', 'pin_code': '682558'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kalpeni', 'village': 'Island', 'pin_code': '682558'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kiltan', 'village': 'Kiltan', 'pin_code': '682559'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Kiltan', 'village': 'Island', 'pin_code': '682559'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Minicoy', 'village': 'Minicoy', 'pin_code': '682560'},
            {'state': 'Lakshadweep', 'district': 'Lakshadweep', 'sub_district': 'Minicoy', 'village': 'Island', 'pin_code': '682560'},
            
            # Delhi
            {'state': 'Delhi', 'district': 'Central Delhi', 'sub_district': 'Central Delhi', 'village': 'Connaught Place', 'pin_code': '110001'},
            {'state': 'Delhi', 'district': 'Central Delhi', 'sub_district': 'Central Delhi', 'village': 'Karol Bagh', 'pin_code': '110005'},
            {'state': 'Delhi', 'district': 'East Delhi', 'sub_district': 'East Delhi', 'village': 'Laxmi Nagar', 'pin_code': '110092'},
            {'state': 'Delhi', 'district': 'East Delhi', 'sub_district': 'East Delhi', 'village': 'Preet Vihar', 'pin_code': '110092'},
            {'state': 'Delhi', 'district': 'New Delhi', 'sub_district': 'New Delhi', 'village': 'Connaught Place', 'pin_code': '110001'},
            {'state': 'Delhi', 'district': 'New Delhi', 'sub_district': 'New Delhi', 'village': 'Lajpat Nagar', 'pin_code': '110024'},
            {'state': 'Delhi', 'district': 'North Delhi', 'sub_district': 'North Delhi', 'village': 'Civil Lines', 'pin_code': '110054'},
            {'state': 'Delhi', 'district': 'North Delhi', 'sub_district': 'North Delhi', 'village': 'Kashmere Gate', 'pin_code': '110006'},
            {'state': 'Delhi', 'district': 'North East Delhi', 'sub_district': 'North East Delhi', 'village': 'Seelampur', 'pin_code': '110053'},
            {'state': 'Delhi', 'district': 'North East Delhi', 'sub_district': 'North East Delhi', 'village': 'Gokulpuri', 'pin_code': '110094'},
            {'state': 'Delhi', 'district': 'North West Delhi', 'sub_district': 'North West Delhi', 'village': 'Rohini', 'pin_code': '110085'},
            {'state': 'Delhi', 'district': 'North West Delhi', 'sub_district': 'North West Delhi', 'village': 'Pitampura', 'pin_code': '110034'},
            {'state': 'Delhi', 'district': 'Shahdara', 'sub_district': 'Shahdara', 'village': 'Shahdara', 'pin_code': '110032'},
            {'state': 'Delhi', 'district': 'Shahdara', 'sub_district': 'Shahdara', 'village': 'Dilshad Garden', 'pin_code': '110095'},
            {'state': 'Delhi', 'district': 'South Delhi', 'sub_district': 'South Delhi', 'village': 'Saket', 'pin_code': '110017'},
            {'state': 'Delhi', 'district': 'South Delhi', 'sub_district': 'South Delhi', 'village': 'Malviya Nagar', 'pin_code': '110017'},
            {'state': 'Delhi', 'district': 'South East Delhi', 'sub_district': 'South East Delhi', 'village': 'Kalkaji', 'pin_code': '110019'},
            {'state': 'Delhi', 'district': 'South East Delhi', 'sub_district': 'South East Delhi', 'village': 'Okhla', 'pin_code': '110020'},
            {'state': 'Delhi', 'district': 'South West Delhi', 'sub_district': 'South West Delhi', 'village': 'Dwarka', 'pin_code': '110075'},
            {'state': 'Delhi', 'district': 'South West Delhi', 'sub_district': 'South West Delhi', 'village': 'Janakpuri', 'pin_code': '110058'},
            {'state': 'Delhi', 'district': 'West Delhi', 'sub_district': 'West Delhi', 'village': 'Rajouri Garden', 'pin_code': '110027'},
            {'state': 'Delhi', 'district': 'West Delhi', 'sub_district': 'West Delhi', 'village': 'Paschim Vihar', 'pin_code': '110063'},
            
            # Gujarat
            {'state': 'Gujarat', 'district': 'Ahmedabad', 'sub_district': 'Ahmedabad City', 'village': 'Navrangpura', 'pin_code': '380009'},
            {'state': 'Gujarat', 'district': 'Ahmedabad', 'sub_district': 'Ahmedabad City', 'village': 'Maninagar', 'pin_code': '380008'},
            {'state': 'Gujarat', 'district': 'Surat', 'sub_district': 'Surat City', 'village': 'Adajan', 'pin_code': '395009'},
            {'state': 'Gujarat', 'district': 'Surat', 'sub_district': 'Surat City', 'village': 'Vesu', 'pin_code': '395007'},
            {'state': 'Gujarat', 'district': 'Vadodara', 'sub_district': 'Vadodara City', 'village': 'Alkapuri', 'pin_code': '390007'},
            {'state': 'Gujarat', 'district': 'Vadodara', 'sub_district': 'Vadodara City', 'village': 'Sayajigunj', 'pin_code': '390005'},
            {'state': 'Gujarat', 'district': 'Rajkot', 'sub_district': 'Rajkot City', 'village': 'Kalavad Road', 'pin_code': '360001'},
            {'state': 'Gujarat', 'district': 'Rajkot', 'sub_district': 'Rajkot City', 'village': 'University Road', 'pin_code': '360005'},
            {'state': 'Gujarat', 'district': 'Gandhinagar', 'sub_district': 'Gandhinagar', 'village': 'Sector 1', 'pin_code': '382001'},
            {'state': 'Gujarat', 'district': 'Gandhinagar', 'sub_district': 'Gandhinagar', 'village': 'Sector 7', 'pin_code': '382007'},
            {'state': 'Gujarat', 'district': 'Bhavnagar', 'sub_district': 'Bhavnagar City', 'village': 'Waghawadi Road', 'pin_code': '364001'},
            {'state': 'Gujarat', 'district': 'Jamnagar', 'sub_district': 'Jamnagar City', 'village': 'Bedipara', 'pin_code': '361001'},
            {'state': 'Gujarat', 'district': 'Junagadh', 'sub_district': 'Junagadh City', 'village': 'Sakkarbaug', 'pin_code': '362001'},
            {'state': 'Gujarat', 'district': 'Anand', 'sub_district': 'Anand', 'village': 'Anand', 'pin_code': '388001'},
            {'state': 'Gujarat', 'district': 'Kheda', 'sub_district': 'Nadiad', 'village': 'Nadiad', 'pin_code': '387001'},
            {'state': 'Gujarat', 'district': 'Mehsana', 'sub_district': 'Mehsana', 'village': 'Mehsana', 'pin_code': '384001'},
            {'state': 'Gujarat', 'district': 'Bharuch', 'sub_district': 'Bharuch', 'village': 'Bharuch', 'pin_code': '392001'},
            {'state': 'Gujarat', 'district': 'Navsari', 'sub_district': 'Navsari', 'village': 'Navsari', 'pin_code': '396445'},
            {'state': 'Gujarat', 'district': 'Valsad', 'sub_district': 'Valsad', 'village': 'Valsad', 'pin_code': '396001'},
            {'state': 'Gujarat', 'district': 'Kutch', 'sub_district': 'Bhuj', 'village': 'Bhuj', 'pin_code': '370001'},
            {'state': 'Gujarat', 'district': 'Porbandar', 'sub_district': 'Porbandar', 'village': 'Porbandar', 'pin_code': '360575'},
            {'state': 'Gujarat', 'district': 'Amreli', 'sub_district': 'Amreli', 'village': 'Amreli', 'pin_code': '365601'},
            {'state': 'Gujarat', 'district': 'Banaskantha', 'sub_district': 'Palanpur', 'village': 'Palanpur', 'pin_code': '385001'},
            {'state': 'Gujarat', 'district': 'Sabarkantha', 'sub_district': 'Himmatnagar', 'village': 'Himmatnagar', 'pin_code': '383001'},
            {'state': 'Gujarat', 'district': 'Panchmahal', 'sub_district': 'Godhra', 'village': 'Godhra', 'pin_code': '389001'},
            {'state': 'Gujarat', 'district': 'Dahod', 'sub_district': 'Dahod', 'village': 'Dahod', 'pin_code': '389151'},
            {'state': 'Gujarat', 'district': 'Narmada', 'sub_district': 'Rajpipla', 'village': 'Rajpipla', 'pin_code': '393145'},
            {'state': 'Gujarat', 'district': 'Tapi', 'sub_district': 'Vyara', 'village': 'Vyara', 'pin_code': '394650'},
            {'state': 'Gujarat', 'district': 'Dang', 'sub_district': 'Ahwa', 'village': 'Ahwa', 'pin_code': '394710'},
            {'state': 'Gujarat', 'district': 'Chhota Udaipur', 'sub_district': 'Chhota Udaipur', 'village': 'Chhota Udaipur', 'pin_code': '391165'},
            {'state': 'Gujarat', 'district': 'Mahisagar', 'sub_district': 'Lunavada', 'village': 'Lunavada', 'pin_code': '389230'},
            {'state': 'Gujarat', 'district': 'Morbi', 'sub_district': 'Morbi', 'village': 'Morbi', 'pin_code': '363641'},
            {'state': 'Gujarat', 'district': 'Botad', 'sub_district': 'Botad', 'village': 'Botad', 'pin_code': '364710'},
            {'state': 'Gujarat', 'district': 'Devbhoomi Dwarka', 'sub_district': 'Dwarka', 'village': 'Dwarka', 'pin_code': '361335'},
            {'state': 'Gujarat', 'district': 'Gir Somnath', 'sub_district': 'Veraval', 'village': 'Veraval', 'pin_code': '362265'},
            {'state': 'Gujarat', 'district': 'Aravalli', 'sub_district': 'Modasa', 'village': 'Modasa', 'pin_code': '383315'},
            {'state': 'Gujarat', 'district': 'Patan', 'sub_district': 'Patan', 'village': 'Patan', 'pin_code': '384265'},
            {'state': 'Gujarat', 'district': 'Surendranagar', 'sub_district': 'Surendranagar', 'village': 'Surendranagar', 'pin_code': '363001'},
            {'state': 'Gujarat', 'district': 'Vav-Tharad', 'sub_district': 'Tharad', 'village': 'Tharad', 'pin_code': '385550'},
            
            # Goa
            {'state': 'Goa', 'district': 'North Goa', 'sub_district': 'Bardez', 'village': 'Panaji', 'pin_code': '403001'},
            {'state': 'Goa', 'district': 'North Goa', 'sub_district': 'Bardez', 'village': 'Mapusa', 'pin_code': '403507'},
            {'state': 'Goa', 'district': 'North Goa', 'sub_district': 'Pernem', 'village': 'Pernem', 'pin_code': '403512'},
            {'state': 'Goa', 'district': 'North Goa', 'sub_district': 'Bicholim', 'village': 'Bicholim', 'pin_code': '403504'},
            {'state': 'Goa', 'district': 'South Goa', 'sub_district': 'Salcete', 'village': 'Margao', 'pin_code': '403601'},
            {'state': 'Goa', 'district': 'South Goa', 'sub_district': 'Salcete', 'village': 'Colva', 'pin_code': '403708'},
            {'state': 'Goa', 'district': 'South Goa', 'sub_district': 'Quepem', 'village': 'Quepem', 'pin_code': '403705'},
            {'state': 'Goa', 'district': 'South Goa', 'sub_district': 'Sanguem', 'village': 'Sanguem', 'pin_code': '403704'},
            
            # Haryana
            {'state': 'Haryana', 'district': 'Gurugram', 'sub_district': 'Gurugram', 'village': 'Sector 29', 'pin_code': '122001'},
            {'state': 'Haryana', 'district': 'Gurugram', 'sub_district': 'Gurugram', 'village': 'Cyber City', 'pin_code': '122002'},
            {'state': 'Haryana', 'district': 'Faridabad', 'sub_district': 'Faridabad', 'village': 'Sector 15', 'pin_code': '121007'},
            {'state': 'Haryana', 'district': 'Faridabad', 'sub_district': 'Faridabad', 'village': 'Ballabgarh', 'pin_code': '121004'},
            {'state': 'Haryana', 'district': 'Panchkula', 'sub_district': 'Panchkula', 'village': 'Sector 5', 'pin_code': '134109'},
            {'state': 'Haryana', 'district': 'Panchkula', 'sub_district': 'Panchkula', 'village': 'Sector 12', 'pin_code': '134112'},
            {'state': 'Haryana', 'district': 'Ambala', 'sub_district': 'Ambala', 'village': 'Ambala City', 'pin_code': '134003'},
            {'state': 'Haryana', 'district': 'Ambala', 'sub_district': 'Ambala', 'village': 'Ambala Cantt', 'pin_code': '133001'},
            {'state': 'Haryana', 'district': 'Karnal', 'sub_district': 'Karnal', 'village': 'Karnal', 'pin_code': '132001'},
            {'state': 'Haryana', 'district': 'Karnal', 'sub_district': 'Karnal', 'village': 'Kunjpura', 'pin_code': '132001'},
            {'state': 'Haryana', 'district': 'Hisar', 'sub_district': 'Hisar', 'village': 'Hisar', 'pin_code': '125001'},
            {'state': 'Haryana', 'district': 'Hisar', 'sub_district': 'Hisar', 'village': 'Hisar Cantt', 'pin_code': '125001'},
            {'state': 'Haryana', 'district': 'Rohtak', 'sub_district': 'Rohtak', 'village': 'Rohtak', 'pin_code': '124001'},
            {'state': 'Haryana', 'district': 'Rohtak', 'sub_district': 'Rohtak', 'village': 'Sampla', 'pin_code': '124001'},
            {'state': 'Haryana', 'district': 'Panipat', 'sub_district': 'Panipat', 'village': 'Panipat', 'pin_code': '132103'},
            {'state': 'Haryana', 'district': 'Panipat', 'sub_district': 'Panipat', 'village': 'Panipat City', 'pin_code': '132103'},
            {'state': 'Haryana', 'district': 'Sonipat', 'sub_district': 'Sonipat', 'village': 'Sonipat', 'pin_code': '131001'},
            {'state': 'Haryana', 'district': 'Sonipat', 'sub_district': 'Sonipat', 'village': 'Murthal', 'pin_code': '131027'},
            {'state': 'Haryana', 'district': 'Yamunanagar', 'sub_district': 'Yamunanagar', 'village': 'Yamunanagar', 'pin_code': '135001'},
            {'state': 'Haryana', 'district': 'Yamunanagar', 'sub_district': 'Yamunanagar', 'village': 'Jagadhri', 'pin_code': '135003'},
            {'state': 'Haryana', 'district': 'Kurukshetra', 'sub_district': 'Kurukshetra', 'village': 'Kurukshetra', 'pin_code': '136118'},
            {'state': 'Haryana', 'district': 'Kurukshetra', 'sub_district': 'Kurukshetra', 'village': 'Thanesar', 'pin_code': '136118'},
            {'state': 'Haryana', 'district': 'Bhiwani', 'sub_district': 'Bhiwani', 'village': 'Bhiwani', 'pin_code': '127021'},
            {'state': 'Haryana', 'district': 'Bhiwani', 'sub_district': 'Bhiwani', 'village': 'Tosham', 'pin_code': '127040'},
            {'state': 'Haryana', 'district': 'Jind', 'sub_district': 'Jind', 'village': 'Jind', 'pin_code': '126102'},
            {'state': 'Haryana', 'district': 'Jind', 'sub_district': 'Jind', 'village': 'Narwana', 'pin_code': '126116'},
            {'state': 'Haryana', 'district': 'Kaithal', 'sub_district': 'Kaithal', 'village': 'Kaithal', 'pin_code': '136027'},
            {'state': 'Haryana', 'district': 'Kaithal', 'sub_district': 'Kaithal', 'village': 'Pundri', 'pin_code': '136027'},
            {'state': 'Haryana', 'district': 'Rewari', 'sub_district': 'Rewari', 'village': 'Rewari', 'pin_code': '123401'},
            {'state': 'Haryana', 'district': 'Rewari', 'sub_district': 'Rewari', 'village': 'Bawal', 'pin_code': '123501'},
            {'state': 'Haryana', 'district': 'Mahendragarh', 'sub_district': 'Mahendragarh', 'village': 'Mahendragarh', 'pin_code': '123029'},
            {'state': 'Haryana', 'district': 'Mahendragarh', 'sub_district': 'Mahendragarh', 'village': 'Narnaul', 'pin_code': '123001'},
            {'state': 'Haryana', 'district': 'Jhajjar', 'sub_district': 'Jhajjar', 'village': 'Jhajjar', 'pin_code': '124103'},
            {'state': 'Haryana', 'district': 'Jhajjar', 'sub_district': 'Jhajjar', 'village': 'Bahadurgarh', 'pin_code': '124507'},
            {'state': 'Haryana', 'district': 'Palwal', 'sub_district': 'Palwal', 'village': 'Palwal', 'pin_code': '121102'},
            {'state': 'Haryana', 'district': 'Palwal', 'sub_district': 'Palwal', 'village': 'Hathin', 'pin_code': '121102'},
            {'state': 'Haryana', 'district': 'Nuh', 'sub_district': 'Nuh', 'village': 'Nuh', 'pin_code': '122107'},
            {'state': 'Haryana', 'district': 'Nuh', 'sub_district': 'Nuh', 'village': 'Firozpur Jhirka', 'pin_code': '122104'},
            {'state': 'Haryana', 'district': 'Fatehabad', 'sub_district': 'Fatehabad', 'village': 'Fatehabad', 'pin_code': '125050'},
            {'state': 'Haryana', 'district': 'Fatehabad', 'sub_district': 'Fatehabad', 'village': 'Tohana', 'pin_code': '125120'},
            {'state': 'Haryana', 'district': 'Sirsa', 'sub_district': 'Sirsa', 'village': 'Sirsa', 'pin_code': '125055'},
            {'state': 'Haryana', 'district': 'Sirsa', 'sub_district': 'Sirsa', 'village': 'Ellenabad', 'pin_code': '125102'},
            {'state': 'Haryana', 'district': 'Charkhi Dadri', 'sub_district': 'Charkhi Dadri', 'village': 'Charkhi Dadri', 'pin_code': '127306'},
            {'state': 'Haryana', 'district': 'Charkhi Dadri', 'sub_district': 'Charkhi Dadri', 'village': 'Badhra', 'pin_code': '127306'},
            
            # Dadra and Nagar Haveli and Daman and Diu
            {'state': 'Dadra and Nagar Haveli and Daman and Diu', 'district': 'Dadra and Nagar Haveli District', 'sub_district': 'Dadra', 'village': 'Dadra', 'pin_code': '396191'},
            {'state': 'Dadra and Nagar Haveli and Daman and Diu', 'district': 'Dadra and Nagar Haveli District', 'sub_district': 'Nagar Haveli', 'village': 'Silvassa', 'pin_code': '396230'},
            {'state': 'Dadra and Nagar Haveli and Daman and Diu', 'district': 'Daman District', 'sub_district': 'Daman', 'village': 'Daman', 'pin_code': '396210'},
            {'state': 'Dadra and Nagar Haveli and Daman and Diu', 'district': 'Diu District', 'sub_district': 'Diu', 'village': 'Diu', 'pin_code': '362520'},
        ]
        
        created_count = 0
        for location_data in sample_locations:
            location, created = IndiaLocation.objects.get_or_create(
                state=location_data['state'],
                district=location_data['district'],
                sub_district=location_data['sub_district'],
                village=location_data['village'],
                pin_code=location_data['pin_code'],
                defaults={
                    'centroid_lat': 19.0760,  # Default coordinates
                    'centroid_lng': 72.8777,
                    'census_code': f"{location_data['state'][:3].upper()}{location_data['district'][:3].upper()}{location_data['sub_district'][:3].upper()}{location_data['village'][:3].upper()}"
                }
            )
            if created:
                created_count += 1
                self.stdout.write(f"Created location: {location}")
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} new locations')
        )
